//// ---
//
//
//// ---
#ifndef COREOBJGENREDEF_H
#define COREOBJGENREDEF_H


#define	CGOG_NOTHING			 0
#define	CGOG_MONEY				 1
#define	CGOG_PLAYER_FACE		 2
#define	CGOG_OBJECT				 3
#define	CGOG_SKILL				 4
#define	CGOG_ITEM				 5
#define	CGOG_NPC				 6
#define	CGOG_MENU_NPC			 7
#define	CGOG_NPC_BLUR			 8
#define	CGOG_MISSLE				 9
#define	CGOG_EQUIP				 10
#define	CGOG_NPCSELLITEM		 11
#define CGOG_PLAYERSELLITEM		 12
#define CGOG_IME_ITEM			 13



#define	CGOG_MAKE_DETAIL(_base, _detail)		(((_detail) << 16) + (_base))
#define	CGOG_EQUIP_CAP			CGOG_MAKE_DETAIL(CGOG_EQUIP, 1)
#define	CGOG_EQUIP_WEAPON		CGOG_MAKE_DETAIL(CGOG_EQUIP, 2)
#define	CGOG_EQUIP_NECKLACE		CGOG_MAKE_DETAIL(CGOG_EQUIP, 3)
#define	CGOG_EQUIP_BANGLE		CGOG_MAKE_DETAIL(CGOG_EQUIP, 4)
#define	CGOG_EQUIP_CLOTHING		CGOG_MAKE_DETAIL(CGOG_EQUIP, 5)
#define	CGOG_EQUIP_CAESTUS		CGOG_MAKE_DETAIL(CGOG_EQUIP, 6)
#define	CGOG_EQUIP_RING			CGOG_MAKE_DETAIL(CGOG_EQUIP, 7)	
#define	CGOG_EQUIP_WAISTDECOR	CGOG_MAKE_DETAIL(CGOG_EQUIP, 8)
#define	CGOG_EQUIP_SHOE			CGOG_MAKE_DETAIL(CGOG_EQUIP, 9)
#define	CGOG_SKILL_LIVE			CGOG_MAKE_DETAIL(CGOG_SKILL, 1)
#define	CGOG_SKILL_FIGHT		CGOG_MAKE_DETAIL(CGOG_SKILL, 2)
#define	CGOG_SKILL_CUSTOM		CGOG_MAKE_DETAIL(CGOG_SKILL, 3)
#define CGOG_SKILL_SHORTCUT		CGOG_MAKE_DETAIL(CGOG_SKILL, 4)
#define	CGOG_ITEM_CORDIAL		CGOG_MAKE_DETAIL(CGOG_ITEM, 1)
//#define	CGOG_ITEM_OTHER			CGOG_MAKE_DETAIL(CGOG_ITEM, 2)
#define	CGOG_NPC_BLUR_DETAIL(x)	CGOG_MAKE_DETAIL(CGOG_NPC_BLUR, x)
#endif
